name: Sameer Garde
favicon: null
layout_spectrum: 0.36594006698578596
typography_spectrum: 0.04405196197330952
title: 'Father, traveller , photographer and runner'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7796a8'
    - '#16363d'
    - '#cacbc4'
    - '#fbf9c1'
  brandStrength: 0.0853656753897667
  lightness: 0.010844007134437561
  saturation: 0.6875
  rhythmicContrast: 0.43222001171670854
purpose: []
